name: inventory_shop
description: Premium offline-first electronics shop inventory and POS application.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  file_picker: ^8.0.7
  csv: ^6.0.0
  excel: ^4.0.6
  pdf: ^3.11.1
  printing: ^5.13.4
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  mobile_scanner: ^5.2.3
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: '>=2.3.7 <2.4.0'

flutter:
  uses-material-design: true
