import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'data/database.dart';
import 'models/models.dart';
import 'theme/app_theme.dart';

void main() async { WidgetsFlutterBinding.ensureInitialized(); await AppDatabase.instance.db; runApp(const InventoryApp()); }

class InventoryApp extends StatelessWidget { const InventoryApp({super.key}); @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Inventory',theme:AppTheme.light(),home:const Shell()); }

class Shell extends StatefulWidget { const Shell({super.key}); @override State<Shell> createState()=>_ShellState(); }
class _ShellState extends State<Shell> { int tab=0; final pages=const [HomePage(),InventoryPage(),PurchasesPage(),SalesPage(),MorePage()]; @override Widget build(BuildContext context){final wide=MediaQuery.sizeOf(context).width>=900; if(wide)return Scaffold(body:Row(children:[NavigationRail(backgroundColor:Colors.white,selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),labelType:NavigationRailLabelType.all,leading:Padding(padding:const EdgeInsets.fromLTRB(8,22,8,28),child:Text('INVENTORY',style:TextStyle(fontWeight:FontWeight.w900,color:AppTheme.blue,letterSpacing:1))),destinations:const [NavigationRailDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:Text('Home')),NavigationRailDestination(icon:Icon(Icons.grid_view_outlined),selectedIcon:Icon(Icons.grid_view),label:Text('Inventory')),NavigationRailDestination(icon:Icon(Icons.local_shipping_outlined),selectedIcon:Icon(Icons.local_shipping),label:Text('Purchases')),NavigationRailDestination(icon:Icon(Icons.point_of_sale_outlined),selectedIcon:Icon(Icons.point_of_sale),label:Text('Sales')),NavigationRailDestination(icon:Icon(Icons.more_horiz),selectedIcon:Icon(Icons.more_horiz),label:Text('More'))]),Expanded(child:pages[tab])],)); return Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.grid_view_outlined),selectedIcon:Icon(Icons.grid_view),label:'Inventory'),NavigationDestination(icon:Icon(Icons.local_shipping_outlined),selectedIcon:Icon(Icons.local_shipping),label:'Purchases'),NavigationDestination(icon:Icon(Icons.point_of_sale_outlined),selectedIcon:Icon(Icons.point_of_sale),label:'Sales'),NavigationDestination(icon:Icon(Icons.more_horiz),selectedIcon:Icon(Icons.more_horiz),label:'More')]));}}

class PageWrap extends StatelessWidget { final Widget child; const PageWrap({super.key,required this.child}); @override Widget build(BuildContext context)=>SafeArea(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:1400),child:Padding(padding:const EdgeInsets.fromLTRB(22,18,22,28),child:child)))); }

class SearchBox extends StatelessWidget { final ValueChanged<String>? onChanged; final String hint; const SearchBox({super.key,this.onChanged,this.hint='Search products, brands, models, SKU...'}); @override Widget build(BuildContext context)=>TextField(onChanged:onChanged,decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:hint,suffixIcon:IconButton(onPressed:(){},icon:const Icon(Icons.tune)))); }

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState()=>_HomePageState(); }
class _HomePageState extends State<HomePage> { Map<String,num> snap={}; List<Product> low=[], top=[]; @override void initState(){super.initState();_load();} Future<void> _load()async{final db=AppDatabase.instance; final s=await db.snapshot(); final p=await db.products(); if(mounted)setState((){snap=s;low=p.where((x)=>x.quantity<=x.minimumStock).take(6).toList();top=p.take(8).toList();});} @override Widget build(BuildContext context)=>PageWrap(child:ListView(children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good morning',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:4),const Text('ElectroMart Electronics',style:TextStyle(color:AppTheme.muted))])),IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none)),const CircleAvatar(child:Text('E'))]),const SizedBox(height:20),SearchBox(onChanged:(q){if(q.isNotEmpty)Navigator.of(context).push(MaterialPageRoute(builder:(_)=>InventoryPage(initialQuery:q)));}),const SizedBox(height:26),const SectionTitle('Categories'),const SizedBox(height:12),SizedBox(height:112,child:ListView(scrollDirection:Axis.horizontal,children:['Mobile Phones','Laptops','Televisions','Refrigerators','Air Conditioners','Washing Machines','Audio','Cameras','Printers','Networking','Storage','Accessories'].map((c)=>CategoryTile(label:c,onTap:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>InventoryPage(category:c)))).toList())),const SizedBox(height:26),const SectionTitle('Business snapshot'),const SizedBox(height:12),Wrap(spacing:12,runSpacing:12,children:[MetricCard('Today’s Sales',money(snap['sales']??0),Icons.point_of_sale_outlined),MetricCard('Today’s Purchases',money(snap['purchases']??0),Icons.local_shipping_outlined),MetricCard('Inventory Value',money(snap['inventory']??0),Icons.inventory_2_outlined),MetricCard('Low Stock','${snap['low']??0} items',Icons.warning_amber_outlined)]),const SizedBox(height:28),Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const SectionTitle('Low stock'),TextButton(onPressed:()=>Navigator.of(context).push(MaterialPageRoute(builder:(_)=>InventoryPage(lowOnly:true))),child:const Text('View all'))]),const SizedBox(height:8),...low.map((p)=>ActivityProduct(p,action:'${p.quantity} units left')),const SizedBox(height:24),const SectionTitle('Top products'),const SizedBox(height:12),SizedBox(height:245,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:top.length,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(_,i)=>ProductCard(product:top[i],width:190))),const SizedBox(height:26),const SectionTitle('Recent activity'),const SizedBox(height:10),const ActivityLine(icon:Icons.add_circle_outline,title:'Opening stock loaded',sub:'Demo store inventory is ready',time:'Today'),const ActivityLine(icon:Icons.shopping_bag_outlined,title:'Stock ledger enabled',sub:'Purchases and sales update stock atomically',time:'Today') ]));}
}

class InventoryPage extends StatefulWidget { final String? initialQuery,category; final bool lowOnly; const InventoryPage({super.key,this.initialQuery,this.category,this.lowOnly=false}); @override State<InventoryPage> createState()=>_InventoryPageState(); }
class _InventoryPageState extends State<InventoryPage>{List<Product> items=[];String q='';bool loading=true; @override void initState(){super.initState();q=widget.initialQuery??'';_load();} Future<void>_load()async{setState(()=>loading=true);final p=await AppDatabase.instance.products(query:q,category:widget.category);if(mounted)setState((){items=widget.lowOnly?p.where((x)=>x.quantity<=x.minimumStock).toList():p;loading=false;});} @override Widget build(BuildContext context)=>PageWrap(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(widget.category??(widget.lowOnly?'Low Stock':'Inventory'),style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800))),FilledButton.icon(onPressed:()=>showAddProduct(context,onSaved:_load),icon:const Icon(Icons.add),label:const Text('Add Product'))]),const SizedBox(height:6),Text('${items.length} products',style:const TextStyle(color:AppTheme.muted)),const SizedBox(height:16),SearchBox(onChanged:(v){q=v;_load();}),const SizedBox(height:16),if(loading)const Expanded(child:Center(child:CircularProgressIndicator())) else Expanded(child:LayoutBuilder(builder:(c,b){final n=b.maxWidth>1100?4:b.maxWidth>700?3:2;return GridView.builder(gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:n,crossAxisSpacing:14,mainAxisSpacing:14,childAspectRatio:.72),itemCount:items.length,itemBuilder:(_,i)=>ProductCard(product:items[i],onTap:()=>showProduct(context,items[i],onChanged:_load));}))]));}

class ProductCard extends StatelessWidget {final Product product;final double? width;final VoidCallback? onTap; const ProductCard({super.key,required this.product,this.width,this.onTap});@override Widget build(BuildContext context)=>SizedBox(width:width,child:Card(child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Container(width:double.infinity,decoration:BoxDecoration(color:AppTheme.bg,borderRadius:BorderRadius.circular(14)),child:Icon(iconFor(product.category),size:62,color:AppTheme.blue))),const SizedBox(height:10),Text(product.brand,style:const TextStyle(fontSize:12,color:AppTheme.muted)),Text(product.name,style:const TextStyle(fontWeight:FontWeight.w700),maxLines:2,overflow:TextOverflow.ellipsis),const SizedBox(height:5),Text(money(product.sellingPrice),style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:4),Row(children:[StockBadge(product.status),const Spacer(),Text('${product.quantity} left',style:const TextStyle(fontSize:11,color:AppTheme.muted))])]))));}

class StockBadge extends StatelessWidget {final String status;const StockBadge(this.status,{super.key});@override Widget build(BuildContext context){final color=status=='IN STOCK'?AppTheme.green:status=='LOW STOCK'?AppTheme.amber:AppTheme.red;return Container(padding:const EdgeInsets.symmetric(horizontal:7,vertical:4),decoration:BoxDecoration(color:color.withOpacity(.1),borderRadius:BorderRadius.circular(20)),child:Text(status,style:TextStyle(color:color,fontSize:9,fontWeight:FontWeight.w800)));}}

class CategoryTile extends StatelessWidget{final String label;final VoidCallback onTap;const CategoryTile({super.key,required this.label,required this.onTap});@override Widget build(BuildContext context)=>Padding(padding:const EdgeInsets.only(right:10),child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(18),child:Container(width:125,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:const Color(0xFFE9EBEF))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(iconFor(label),color:AppTheme.blue,size:30),const Spacer(),Text(label,style:const TextStyle(fontWeight:FontWeight.w700),maxLines:2)]))));}

class SectionTitle extends StatelessWidget{final String text;const SectionTitle(this.text,{super.key});@override Widget build(BuildContext context)=>Text(text,style:Theme.of(context).textTheme.titleLarge?.copyWith(fontWeight:FontWeight.w800));}
class MetricCard extends StatelessWidget{final String title,value;final IconData icon;const MetricCard(this.title,this.value,this.icon,{super.key});@override Widget build(BuildContext context)=>SizedBox(width:220,child:Card(child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:AppTheme.blue.withOpacity(.09),borderRadius:BorderRadius.circular(12)),child:Icon(icon,color:AppTheme.blue)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontSize:12,color:AppTheme.muted)),const SizedBox(height:5),Text(value,style:const TextStyle(fontSize:18,fontWeight:FontWeight.w800))]))]))));}
class ActivityProduct extends StatelessWidget{final Product p;final String action;const ActivityProduct(this.p,{super.key,required this.action});@override Widget build(BuildContext context)=>Card(child:ListTile(leading:CircleAvatar(backgroundColor:AppTheme.bg,child:Icon(iconFor(p.category),color:AppTheme.blue)),title:Text('${p.brand} · ${p.name}',maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text(action),trailing:StockBadge(p.status),onTap:()=>showProduct(context,p)));}
class ActivityLine extends StatelessWidget{final IconData icon;final String title,sub,time;const ActivityLine({super.key,required this.icon,required this.title,required this.sub,required this.time});@override Widget build(BuildContext context)=>ListTile(contentPadding:EdgeInsets.zero,leading:CircleAvatar(backgroundColor:AppTheme.blue.withOpacity(.09),child:Icon(icon,color:AppTheme.blue)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),subtitle:Text(sub),trailing:Text(time,style:const TextStyle(color:AppTheme.muted,fontSize:12)));}

class PurchasesPage extends StatelessWidget{const PurchasesPage({super.key});@override Widget build(BuildContext context)=>PageWrap(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Purchases',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:6),const Text('Supplier invoices and incoming stock',style:TextStyle(color:AppTheme.muted)),const SizedBox(height:22),Card(child:Padding(padding:const EdgeInsets.all(20),child:Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('New purchase',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),SizedBox(height:5),Text('Receive products and update the stock ledger automatically.',style:TextStyle(color:AppTheme.muted))])),FilledButton.icon(onPressed:()=>showPurchase(context),icon:const Icon(Icons.add),label:const Text('New Purchase'))])),const SizedBox(height:16),const ActivityLine(icon:Icons.receipt_long,title:'Purchase workflow ready',sub:'Supplier, invoice, quantity, cost, GST and payment fields',time:'Now'),const ActivityLine(icon:Icons.inventory_2,title:'Atomic stock updates',sub:'Purchases increase inventory and create ledger entries',time:'Now')]));}

class SalesPage extends StatefulWidget{const SalesPage({super.key});@override State<SalesPage>createState()=>_SalesPageState();}
class _SalesPageState extends State<SalesPage>{@override Widget build(BuildContext context)=>PageWrap(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Sales',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const Text('Fast POS for everyday counter sales',style:TextStyle(color:AppTheme.muted))])),FilledButton.icon(onPressed:()=>showPOS(context),icon:const Icon(Icons.point_of_sale),label:const Text('New Sale'))]),const SizedBox(height:20),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Fast checkout',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:8),const Text('Search or scan a product, choose quantity and complete payment. Stock is deducted inside the same database transaction.',style:TextStyle(color:AppTheme.muted)),const SizedBox(height:16),FilledButton.icon(onPressed:()=>showPOS(context),icon:const Icon(Icons.shopping_cart_checkout),label:const Text('Open POS'))]))]));}}

class MorePage extends StatelessWidget{const MorePage({super.key});@override Widget build(BuildContext context)=>PageWrap(child:ListView(children:[Text('More',style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:16),...['Customers','Suppliers','Expenses','Reports','Monthly Books','Warranty','Dead Stock','Backup & Restore','Settings','Users','Notifications'].map((x)=>Card(child:ListTile(leading:Icon(iconFor(x),color:AppTheme.blue),title:Text(x,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:const Icon(Icons.chevron_right),onTap:(){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('$x is available in the app architecture.')));}))) ]));}

Future<void> showProduct(BuildContext context,Product p,{VoidCallback? onChanged})async{await showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(22),child:Wrap(children:[Row(children:[Expanded(child:Text(p.name,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w800))),StockBadge(p.status)]),Text('${p.brand} · ${p.category}',style:const TextStyle(color:AppTheme.muted)),const SizedBox(height:18),Row(children:[Expanded(child:Text(money(p.sellingPrice),style:const TextStyle(fontSize:28,fontWeight:FontWeight.w900))),Text('Cost ${money(p.purchasePrice)}\nProfit ${money(p.profit)}',textAlign:TextAlign.right)]),const SizedBox(height:18),Text('Stock: ${p.quantity}   •   Minimum: ${p.minimumStock}'),Text('SKU: ${p.sku}   •   Model: ${p.model}'),Text('Supplier: ${p.supplier}   •   Warranty: ${p.warranty}'),const SizedBox(height:18),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>showAdjust(context,p,onChanged),icon:const Icon(Icons.add_box_outlined),label:const Text('Add Stock'))),const SizedBox(width:10),Expanded(child:FilledButton.icon(onPressed:()=>showSell(context,p,onChanged),icon:const Icon(Icons.point_of_sale),label:const Text('Sell')))])])));}
Future<void> showAdjust(BuildContext context,Product p,VoidCallback? changed)async{final c=TextEditingController();await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Adjust Stock'),content:TextField(controller:c,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity to add',prefixIcon:Icon(Icons.add))),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()async{final n=int.tryParse(c.text)??0;if(n>0){await AppDatabase.instance.adjustStock(p,n,'Manual stock receipt');changed?.call();Navigator.pop(context);Navigator.pop(context);} },child:const Text('Add Stock'))]));}
Future<void> showSell(BuildContext context,Product p,VoidCallback? changed)async{final c=TextEditingController(text:'1');await showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Sell Product'),content:TextField(controller:c,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'Quantity (max ${p.quantity})')),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:()async{final n=int.tryParse(c.text)??0;try{await AppDatabase.instance.sell(p,n);changed?.call();Navigator.pop(context);Navigator.pop(context);if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Sale completed and stock updated.')));}catch(e){if(context.mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}},child:const Text('Complete Sale'))]));}
Future<void> showAddProduct(BuildContext context,{VoidCallback? onSaved})async{final name=TextEditingController(),brand=TextEditingController(),cat=TextEditingController(),price=TextEditingController(),cost=TextEditingController(),qty=TextEditingController(text:'1');await showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>Padding(padding:EdgeInsets.fromLTRB(20,10,20,MediaQuery.viewInsetsOf(context).bottom+20),child:Wrap(runSpacing:10,children:[const Text('Add Product',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),TextField(controller:name,decoration:const InputDecoration(labelText:'Product Name')),TextField(controller:brand,decoration:const InputDecoration(labelText:'Brand')),TextField(controller:cat,decoration:const InputDecoration(labelText:'Category')),Row(children:[Expanded(child:TextField(controller:cost,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Purchase Price'))),const SizedBox(width:10),Expanded(child:TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Selling Price')))]),TextField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Opening Quantity')),FilledButton(onPressed:()async{final n=name.text.trim(),b=brand.text.trim(),ca=cat.text.trim();final sp=double.tryParse(price.text)??0,cp=double.tryParse(cost.text)??0,q=int.tryParse(qty.text)??0;if(n.isEmpty||b.isEmpty||ca.isEmpty||sp<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Please enter product, brand, category and a valid selling price.')));return;}final db=await AppDatabase.instance.db;final sku='${b.substring(0,b.length>3?3:b.length).toUpperCase()}-${DateTime.now().millisecondsSinceEpoch.toString().substring(7)}';final id=await db.insert('products',{'name':n,'brand':b,'category':ca,'model':'','sku':sku,'barcode':'','mrp':sp,'selling_price':sp,'purchase_price':cp,'quantity':q,'minimum_stock':2,'supplier':'','warranty':'','specs':'','created_at':DateTime.now().toIso8601String(),'updated_at':DateTime.now().toIso8601String()});if(q>0)await db.insert('stock_movements',{'product_id':id,'quantity':q,'type':'OPENING_STOCK','date':DateTime.now().toIso8601String(),'note':'Opening stock','cost':cp});if(context.mounted){Navigator.pop(context);onSaved?.call();}},child:const Text('Save Product'))])));}
Future<void> showPOS(BuildContext context)async{final p=await AppDatabase.instance.products();if(!context.mounted)return;await showModalBottomSheet(context:context,isScrollControlled:true,showDragHandle:true,builder:(_)=>SizedBox(height:MediaQuery.sizeOf(context).height*.85,child:StatefulBuilder(builder:(context,set){String q='';List<Product> shown=p;return Padding(padding:const EdgeInsets.all(20),child:Column(children:[const Text('New Sale',style:TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:14),SearchBox(hint:'Search or scan product',onChanged:(v){set((){q=v;shown=p.where((x)=>x.name.toLowerCase().contains(q.toLowerCase())||x.brand.toLowerCase().contains(q.toLowerCase())||x.sku.toLowerCase().contains(q.toLowerCase())).toList();});}),const SizedBox(height:12),Expanded(child:ListView(children:shown.map((x)=>ListTile(leading:CircleAvatar(child:Icon(iconFor(x.category))),title:Text(x.name),subtitle:Text('${x.brand} · ${money(x.sellingPrice)} · ${x.quantity} in stock'),trailing:IconButton(icon:const Icon(Icons.add_circle),onPressed:()=>showSell(context,x,null))).toList()))]));})));}
Future<void> showPurchase(BuildContext context)async{showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('New Purchase'),content:const Text('Purchase entry is structured for supplier, invoice, products, GST, payment and atomic stock updates. Use Add Stock on a product for a quick receipt.'),actions:[FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('Got it'))]));}
String money(num n)=>NumberFormat.currency(locale:'en_IN',symbol:'₹',decimalDigits:0).format(n);
IconData iconFor(String s){final x=s.toLowerCase();if(x.contains('mobile'))return Icons.smartphone;if(x.contains('laptop'))return Icons.laptop;if(x.contains('tv')||x.contains('television'))return Icons.tv;if(x.contains('refrigerator'))return Icons.kitchen;if(x.contains('air conditioner'))return Icons.ac_unit;if(x.contains('washing'))return Icons.local_laundry_service;if(x.contains('audio'))return Icons.headphones;if(x.contains('camera'))return Icons.camera_alt;if(x.contains('printer'))return Icons.print;if(x.contains('network'))return Icons.router;if(x.contains('storage'))return Icons.storage;if(x.contains('expense'))return Icons.payments;if(x.contains('customer'))return Icons.people_outline;if(x.contains('supplier'))return Icons.local_shipping_outlined;if(x.contains('report'))return Icons.bar_chart;if(x.contains('warranty'))return Icons.verified_user_outlined;if(x.contains('dead'))return Icons.inventory_2_outlined;if(x.contains('backup'))return Icons.backup;if(x.contains('setting'))return Icons.settings;if(x.contains('user'))return Icons.manage_accounts;return Icons.devices_other;}
